Terminal session started on gisapp-omf-01 at Fri, Oct 25, 2024  5:53:28 PM
[2024-10-25 17:53:29] Command: source terminal-logger.sh 
Terminal session resumed on gisapp-omf-01 at Fri, Oct 25, 2024  5:53:30 PM
[2024-10-25 17:53:30] Output: Logging enabled - all commands will be logged to /c/Users/A.A919579/Samantha/iamanarcpygenius/data/output/logs/terminal_gisapp-omf-01.log
[2024-10-25 17:53:43] Command: python -m scripts.cli verify
[2024-10-25 17:53:47] Output: 2024-10-25 17:53:47,484 - scripts.helpers.verify_setup - INFO - Starting environment verification...
[2024-10-25 17:53:48] Output: 2024-10-25 17:53:47,484 - scripts.helpers.verify_setup - INFO - Python version: 3.7.11
[2024-10-25 17:53:48] Output: 2024-10-25 17:53:47,484 - scripts.helpers.verify_setup - INFO - \u2713 arcpy (for ArcGIS installation)
[2024-10-25 17:53:48] Output: 2024-10-25 17:53:47,484 - scripts.helpers.verify_setup - INFO - \u2713 click (for CLI support)
[2024-10-25 17:53:48] Output: 2024-10-25 17:53:48,350 - scripts.helpers.verify_setup - INFO - \u2713 pandas (for Data processing)
[2024-10-25 17:53:49] Output: 2024-10-25 17:53:48,350 - scripts.helpers.verify_setup - INFO - \u2713 yaml (for Configuration)
[2024-10-25 17:53:49] Output: 2024-10-25 17:53:48,415 - scripts.helpers.verify_setup - ERROR - \u2717 pytest (for Testing)
[2024-10-25 17:53:49] Output: 2024-10-25 17:53:48,415 - scripts.helpers.verify_setup - INFO - \u2713 ArcPy environment configured successfully
[2024-10-25 17:53:49] Output: 2024-10-25 17:53:48,418 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\input\mxd
[2024-10-25 17:53:49] Output: 2024-10-25 17:53:48,418 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\input\aprx
[2024-10-25 17:53:50] Output: 2024-10-25 17:53:48,418 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\output\pdf
[2024-10-25 17:53:50] Output: 2024-10-25 17:53:48,418 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\output\logs
[2024-10-25 17:53:50] Output: 2024-10-25 17:53:48,419 - scripts.helpers.verify_setup - ERROR - \u2717 Some verification checks failed
[2024-10-25 17:53:50] Output: Environment verification failed. Check the logs for details.
[2024-10-25 17:55:16] Command: python -m pip list | findstr "pytest"
[2024-10-25 17:55:18] Output: pytest                            7.4.4
[2024-10-25 17:55:19] Output: pytest-cov                        4.1.0
[2024-10-25 17:55:19] Command: python -m pip list | findstr "pytest"
[2024-10-25 17:55:22] Output: pytest                            7.4.4
[2024-10-25 17:55:23] Output: pytest-cov                        4.1.0
[2024-10-25 17:55:53] Command: python -m pip install --force-reinstall pytest pytest-cov
[2024-10-25 17:55:55] Output: Collecting pytest
[2024-10-25 17:55:55] Output: Downloading pytest-7.4.4-py3-none-any.whl.metadata (7.9 kB)
[2024-10-25 17:55:56] Output: Collecting pytest-cov
[2024-10-25 17:55:56] Output: Downloading pytest_cov-4.1.0-py3-none-any.whl.metadata (26 kB)
[2024-10-25 17:55:57] Output: Collecting iniconfig (from pytest)
[2024-10-25 17:55:57] Output: Downloading iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
[2024-10-25 17:55:57] Output: Collecting packaging (from pytest)
[2024-10-25 17:55:58] Output: Downloading packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
[2024-10-25 17:55:58] Output: Collecting pluggy<2.0,>=0.12 (from pytest)
[2024-10-25 17:55:58] Output: Downloading pluggy-1.2.0-py3-none-any.whl.metadata (4.4 kB)
[2024-10-25 17:55:59] Output: Collecting exceptiongroup>=1.0.0rc8 (from pytest)
[2024-10-25 17:55:59] Output: Downloading exceptiongroup-1.2.2-py3-none-any.whl.metadata (6.6 kB)
[2024-10-25 17:56:00] Output: Collecting tomli>=1.0.0 (from pytest)
[2024-10-25 17:56:00] Output: Downloading tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
[2024-10-25 17:56:00] Output: Collecting importlib-metadata>=0.12 (from pytest)
[2024-10-25 17:56:00] Output: Downloading importlib_metadata-6.7.0-py3-none-any.whl.metadata (4.9 kB)
[2024-10-25 17:56:01] Output: Collecting colorama (from pytest)
[2024-10-25 17:56:01] Output: Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
[2024-10-25 17:56:01] Output: Collecting coverage>=5.2.1 (from coverage[toml]>=5.2.1->pytest-cov)
[2024-10-25 17:56:01] Output: Downloading coverage-7.2.7-cp37-cp37m-win_amd64.whl.metadata (9.9 kB)
[2024-10-25 17:56:02] Output: Collecting zipp>=0.5 (from importlib-metadata>=0.12->pytest)
[2024-10-25 17:56:02] Output: Downloading zipp-3.15.0-py3-none-any.whl.metadata (3.7 kB)
[2024-10-25 17:56:03] Output: Collecting typing-extensions>=3.6.4 (from importlib-metadata>=0.12->pytest)
[2024-10-25 17:56:03] Output: Downloading typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
[2024-10-25 17:56:03] Output: Downloading pytest-7.4.4-py3-none-any.whl (325 kB)
[2024-10-25 17:56:04] Output: ---------------------------------------- 325.3/325.3 kB 1.1 MB/s eta 0:00:00
[2024-10-25 17:56:04] Output: Downloading pytest_cov-4.1.0-py3-none-any.whl (21 kB)
[2024-10-25 17:56:04] Output: Downloading coverage-7.2.7-cp37-cp37m-win_amd64.whl (204 kB)
[2024-10-25 17:56:05] Output: ---------------------------------------- 204.0/204.0 kB 3.1 MB/s eta 0:00:00
[2024-10-25 17:56:05] Output: Downloading exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
[2024-10-25 17:56:06] Output: Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
[2024-10-25 17:56:06] Output: Downloading pluggy-1.2.0-py3-none-any.whl (17 kB)
[2024-10-25 17:56:06] Output: Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
[2024-10-25 17:56:07] Output: Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
[2024-10-25 17:56:07] Output: Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
[2024-10-25 17:56:07] Output: Downloading packaging-24.0-py3-none-any.whl (53 kB)
[2024-10-25 17:56:08] Output: ---------------------------------------- 53.5/53.5 kB 2.7 MB/s eta 0:00:00
[2024-10-25 17:56:09] Output: Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
[2024-10-25 17:56:09] Output: Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
[2024-10-25 17:56:10] Output: DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
[2024-10-25 17:56:11] Output: Installing collected packages: zipp, typing-extensions, tomli, packaging, iniconfig, exceptiongroup, coverage, colorama, importlib-metadata, pluggy, pytest, pytest-cov
[2024-10-25 17:56:11] Output: Attempting uninstall: zipp
[2024-10-25 17:56:11] Output: Found existing installation: zipp 3.4.1
[2024-10-25 17:56:12] Output: Uninstalling zipp-3.4.1:
[2024-10-25 17:56:13] Output: Successfully uninstalled zipp-3.4.1
[2024-10-25 17:56:13] Output: Attempting uninstall: typing-extensions
[2024-10-25 17:56:14] Output: Found existing installation: typing-extensions 3.7.4.3
[2024-10-25 17:56:15] Output: Uninstalling typing-extensions-3.7.4.3:
[2024-10-25 17:56:16] Output: Successfully uninstalled typing-extensions-3.7.4.3
[2024-10-25 17:56:17] Output: Attempting uninstall: packaging
[2024-10-25 17:56:17] Output: Found existing installation: packaging 20.9
[2024-10-25 17:56:17] Output: Uninstalling packaging-20.9:
[2024-10-25 17:56:18] Output: Successfully uninstalled packaging-20.9
[2024-10-25 17:56:18] Output: Attempting uninstall: iniconfig
[2024-10-25 17:56:18] Output: Found existing installation: iniconfig 1.1.1
[2024-10-25 17:56:18] Output: Uninstalling iniconfig-1.1.1:
[2024-10-25 17:56:19] Output: Successfully uninstalled iniconfig-1.1.1
[2024-10-25 17:56:19] Output: Attempting uninstall: colorama
[2024-10-25 17:56:19] Output: Found existing installation: colorama 0.4.4
[2024-10-25 17:56:19] Output: Uninstalling colorama-0.4.4:
[2024-10-25 17:56:20] Output: Successfully uninstalled colorama-0.4.4
[2024-10-25 17:56:20] Output: Attempting uninstall: importlib-metadata
[2024-10-25 17:56:20] Output: Found existing installation: importlib-metadata 3.7.3
[2024-10-25 17:56:20] Output: Uninstalling importlib-metadata-3.7.3:
[2024-10-25 17:56:21] Output: Successfully uninstalled importlib-metadata-3.7.3
[2024-10-25 17:56:21] Output: Attempting uninstall: pluggy
[2024-10-25 17:56:21] Output: Found existing installation: pluggy 0.13.1
[2024-10-25 17:56:22] Output: Uninstalling pluggy-0.13.1:
[2024-10-25 17:56:22] Output: Successfully uninstalled pluggy-0.13.1
[2024-10-25 17:56:22] Output: Attempting uninstall: pytest
[2024-10-25 17:56:23] Output: Found existing installation: pytest 7.4.4
[2024-10-25 17:56:23] Output: Uninstalling pytest-7.4.4:
[2024-10-25 17:56:23] Output: Successfully uninstalled pytest-7.4.4
[2024-10-25 17:56:24] Output: Attempting uninstall: pytest-cov
[2024-10-25 17:56:25] Output: Found existing installation: pytest-cov 4.1.0
[2024-10-25 17:56:25] Output: Uninstalling pytest-cov-4.1.0:
[2024-10-25 17:56:25] Output: Successfully uninstalled pytest-cov-4.1.0
[2024-10-25 17:56:26] Output: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-10-25 17:56:26] Output: flake8 3.9.0 requires pycodestyle<2.8.0,>=2.7.0, but you have pycodestyle 2.6.0 which is incompatible.
[2024-10-25 17:56:27] Output: flake8 3.9.0 requires pyflakes<2.4.0,>=2.3.0, but you have pyflakes 2.2.0 which is incompatible.
[2024-10-25 17:56:27] Output: Successfully installed colorama-0.4.6 coverage-7.2.7 exceptiongroup-1.2.2 importlib-metadata-6.7.0 iniconfig-2.0.0 packaging-24.0 pluggy-1.2.0 pytest-7.4.4 pytest-cov-4.1.0 tomli-2.0.1 typing-extensions-4.7.1 zipp-3.15.0
[2024-10-25 17:57:30] Command: python -m pytest --version
[2024-10-25 17:57:32] Output: pytest 7.4.4
[2024-10-25 17:57:47] Command: python -m scripts.cli verify
[2024-10-25 17:57:51] Output: 2024-10-25 17:57:50,948 - scripts.helpers.verify_setup - INFO - Starting environment verification...
[2024-10-25 17:57:51] Output: 2024-10-25 17:57:50,948 - scripts.helpers.verify_setup - INFO - Python version: 3.7.11
[2024-10-25 17:57:51] Output: 2024-10-25 17:57:50,948 - scripts.helpers.verify_setup - INFO - \u2713 arcpy (for ArcGIS installation)
[2024-10-25 17:57:51] Output: 2024-10-25 17:57:50,948 - scripts.helpers.verify_setup - INFO - \u2713 click (for CLI support)
[2024-10-25 17:57:52] Output: 2024-10-25 17:57:51,646 - scripts.helpers.verify_setup - INFO - \u2713 pandas (for Data processing)
[2024-10-25 17:57:52] Output: 2024-10-25 17:57:51,646 - scripts.helpers.verify_setup - INFO - \u2713 yaml (for Configuration)
[2024-10-25 17:57:52] Output: 2024-10-25 17:57:51,845 - scripts.helpers.verify_setup - INFO - \u2713 pytest (for Testing)
[2024-10-25 17:57:52] Output: 2024-10-25 17:57:51,845 - scripts.helpers.verify_setup - INFO - \u2713 ArcPy environment configured successfully
[2024-10-25 17:57:52] Output: 2024-10-25 17:57:51,847 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\input\mxd
[2024-10-25 17:57:53] Output: 2024-10-25 17:57:51,848 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\input\aprx
[2024-10-25 17:57:53] Output: 2024-10-25 17:57:51,848 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\output\pdf
[2024-10-25 17:57:53] Output: 2024-10-25 17:57:51,848 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\output\logs
[2024-10-25 17:57:54] Output: 2024-10-25 17:57:51,848 - scripts.helpers.verify_setup - INFO - \u2713 All verification checks passed
[2024-10-25 17:57:54] Output: Environment verification successful!
[2024-10-25 17:59:32] Command: python -m pytest -v
[2024-10-25 17:59:34] Output: ============================= test session starts =============================
[2024-10-25 17:59:34] Output: platform win32 -- Python 3.7.11, pytest-7.4.4, pluggy-1.2.0 -- C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\python.exe
[2024-10-25 17:59:34] Output: cachedir: .pytest_cache
[2024-10-25 17:59:35] Output: rootdir: C:\Users\A.A919579\Samantha\iamanarcpygenius
[2024-10-25 17:59:35] Output: plugins: cov-4.1.0
[2024-10-25 17:59:37] Output: collecting ... Windows fatal exception: code 0xe0000001
[2024-10-25 17:59:37] Output: 
[2024-10-25 17:59:37] Output: Current thread 0x000029ec (most recent call first):
[2024-10-25 17:59:38] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 70 in __init__
[2024-10-25 17:59:38] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 617 in <module>
[2024-10-25 17:59:39] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 17:59:39] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 17:59:39] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 17:59:40] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 17:59:40] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 17:59:40] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14 in <module>
[2024-10-25 17:59:41] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 17:59:42] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 17:59:42] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 17:59:42] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 17:59:43] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 17:59:43] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 88 in <module>
[2024-10-25 17:59:44] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 17:59:44] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 17:59:45] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 17:59:45] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 17:59:46] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 17:59:46] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\process_mxd.py", line 1 in <module>
[2024-10-25 17:59:47] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 17:59:47] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 17:59:48] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 17:59:48] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 17:59:48] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 17:59:49] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\file_handler.py", line 4 in <module>
[2024-10-25 17:59:49] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 17:59:49] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 17:59:50] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 17:59:50] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 17:59:51] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 17:59:51] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\tests\test_file_handler.py", line 3 in <module>
[2024-10-25 17:59:52] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\assertion\rewrite.py", line 186 in exec_module
[2024-10-25 17:59:52] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 17:59:52] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 17:59:53] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 17:59:54] Output: File "<frozen importlib._bootstrap>", line 1006 in _gcd_import
[2024-10-25 17:59:54] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\importlib\__init__.py", line 127 in import_module
[2024-10-25 17:59:55] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\pathlib.py", line 567 in import_path
[2024-10-25 17:59:56] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 617 in _importtestmodule
[2024-10-25 17:59:57] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 528 in _getobj
[2024-10-25 17:59:57] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 310 in obj
[2024-10-25 17:59:58] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 545 in _inject_setup_module_fixture
[2024-10-25 17:59:58] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 531 in collect
[2024-10-25 17:59:59] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in <lambda>
[2024-10-25 18:00:00] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 341 in from_call
[2024-10-25 18:00:02] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in pytest_make_collect_report
[2024-10-25 18:00:03] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:00:04] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:00:06] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:00:07] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 547 in collect_one_node
[2024-10-25 18:00:08] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 842 in genitems
[2024-10-25 18:00:09] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 675 in perform_collect
[2024-10-25 18:00:10] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 335 in pytest_collection
[2024-10-25 18:00:11] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:00:12] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:00:13] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:00:13] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 324 in _main
[2024-10-25 18:00:14] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 271 in wrap_session
[2024-10-25 18:00:15] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 318 in pytest_cmdline_main
[2024-10-25 18:00:15] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:00:16] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:00:17] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:00:17] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 170 in main
[2024-10-25 18:00:18] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 192 in console_main
[2024-10-25 18:00:19] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pytest\__main__.py", line 5 in <module>
[2024-10-25 18:00:19] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 85 in _run_code
[2024-10-25 18:00:20] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 193 in _run_module_as_main
[2024-10-25 18:00:20] Output: Windows fatal exception: code 0xe0000001
[2024-10-25 18:00:21] Output: 
[2024-10-25 18:00:21] Output: Current thread 0x000029ec (most recent call first):
[2024-10-25 18:00:22] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 70 in __init__
[2024-10-25 18:00:22] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 617 in <module>
[2024-10-25 18:00:23] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:00:23] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:00:24] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:00:24] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:00:25] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:00:26] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14 in <module>
[2024-10-25 18:00:26] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:00:27] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:00:27] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:00:28] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:00:28] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:00:28] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 88 in <module>
[2024-10-25 18:00:29] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:00:30] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:00:30] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:00:30] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:00:31] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:00:31] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\process_mxd.py", line 1 in <module>
[2024-10-25 18:00:31] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:00:32] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:00:32] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:00:33] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:00:33] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:00:33] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\file_handler.py", line 4 in <module>
[2024-10-25 18:00:34] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:00:35] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:00:36] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:00:36] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:00:37] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:00:37] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\tests\test_file_handler.py", line 3 in <module>
[2024-10-25 18:00:38] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\assertion\rewrite.py", line 186 in exec_module
[2024-10-25 18:00:38] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:00:39] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:00:39] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:00:39] Output: File "<frozen importlib._bootstrap>", line 1006 in _gcd_import
[2024-10-25 18:00:40] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\importlib\__init__.py", line 127 in import_module
[2024-10-25 18:00:40] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\pathlib.py", line 567 in import_path
[2024-10-25 18:00:41] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 617 in _importtestmodule
[2024-10-25 18:00:42] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 528 in _getobj
[2024-10-25 18:00:42] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 310 in obj
[2024-10-25 18:00:43] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 545 in _inject_setup_module_fixture
[2024-10-25 18:00:44] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 531 in collect
[2024-10-25 18:00:45] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in <lambda>
[2024-10-25 18:00:45] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 341 in from_call
[2024-10-25 18:00:46] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in pytest_make_collect_report
[2024-10-25 18:00:47] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:00:48] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:00:48] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:00:48] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 547 in collect_one_node
[2024-10-25 18:00:49] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 842 in genitems
[2024-10-25 18:00:49] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 675 in perform_collect
[2024-10-25 18:00:50] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 335 in pytest_collection
[2024-10-25 18:00:50] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:00:51] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:00:51] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:00:52] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 324 in _main
[2024-10-25 18:00:52] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 271 in wrap_session
[2024-10-25 18:00:53] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 318 in pytest_cmdline_main
[2024-10-25 18:00:54] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:00:54] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:00:55] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:00:55] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 170 in main
[2024-10-25 18:00:56] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 192 in console_main
[2024-10-25 18:00:57] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pytest\__main__.py", line 5 in <module>
[2024-10-25 18:00:57] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 85 in _run_code
[2024-10-25 18:00:58] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 193 in _run_module_as_main
[2024-10-25 18:00:58] Output: Windows fatal exception: code 0xe0000001
[2024-10-25 18:00:59] Output: 
[2024-10-25 18:00:59] Output: Current thread 0x000029ec (most recent call first):
[2024-10-25 18:00:59] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 70 in __init__
[2024-10-25 18:01:00] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 617 in <module>
[2024-10-25 18:01:01] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:01:01] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:01:02] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:01:02] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:01:03] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:01:03] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14 in <module>
[2024-10-25 18:01:04] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:01:04] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:01:05] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:01:05] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:01:06] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:01:07] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 88 in <module>
[2024-10-25 18:01:07] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:01:08] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:01:08] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:01:18] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:01:19] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:01:19] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\process_mxd.py", line 1 in <module>
[2024-10-25 18:01:20] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:01:20] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:01:21] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:01:21] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:01:22] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:01:22] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\file_handler.py", line 4 in <module>
[2024-10-25 18:01:23] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:01:24] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:01:24] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:01:24] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:01:25] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:01:26] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\tests\test_file_handler.py", line 3 in <module>
[2024-10-25 18:01:27] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\assertion\rewrite.py", line 186 in exec_module
[2024-10-25 18:01:27] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:01:28] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:01:28] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:01:28] Output: File "<frozen importlib._bootstrap>", line 1006 in _gcd_import
[2024-10-25 18:01:29] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\importlib\__init__.py", line 127 in import_module
[2024-10-25 18:01:29] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\pathlib.py", line 567 in import_path
[2024-10-25 18:01:30] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 617 in _importtestmodule
[2024-10-25 18:01:30] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 528 in _getobj
[2024-10-25 18:01:31] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 310 in obj
[2024-10-25 18:01:32] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 545 in _inject_setup_module_fixture
[2024-10-25 18:01:33] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 531 in collect
[2024-10-25 18:01:33] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in <lambda>
[2024-10-25 18:01:34] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 341 in from_call
[2024-10-25 18:01:35] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in pytest_make_collect_report
[2024-10-25 18:01:36] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:01:36] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:01:37] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:01:38] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 547 in collect_one_node
[2024-10-25 18:01:38] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 842 in genitems
[2024-10-25 18:01:39] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 675 in perform_collect
[2024-10-25 18:01:40] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 335 in pytest_collection
[2024-10-25 18:01:41] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:01:41] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:01:42] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:01:42] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 324 in _main
[2024-10-25 18:01:43] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 271 in wrap_session
[2024-10-25 18:01:44] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 318 in pytest_cmdline_main
[2024-10-25 18:01:45] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:01:46] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:01:46] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:01:47] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 170 in main
[2024-10-25 18:01:48] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 192 in console_main
[2024-10-25 18:01:48] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pytest\__main__.py", line 5 in <module>
[2024-10-25 18:01:49] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 85 in _run_code
[2024-10-25 18:01:49] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 193 in _run_module_as_main
[2024-10-25 18:01:50] Output: Windows fatal exception: code 0xe0000001
[2024-10-25 18:01:50] Output: 
[2024-10-25 18:01:50] Output: Current thread 0x000029ec (most recent call first):
[2024-10-25 18:01:51] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 70 in __init__
[2024-10-25 18:01:52] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 617 in <module>
[2024-10-25 18:01:52] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:01:52] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:01:53] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:01:53] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:01:54] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:01:54] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14 in <module>
[2024-10-25 18:01:55] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:01:55] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:01:56] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:01:56] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:01:57] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:01:57] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 88 in <module>
[2024-10-25 18:01:58] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:01:58] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:01:59] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:01:59] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:02:00] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:02:01] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\process_mxd.py", line 1 in <module>
[2024-10-25 18:02:01] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:02:01] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:02:02] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:02:02] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:02:02] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:02:03] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\file_handler.py", line 4 in <module>
[2024-10-25 18:02:03] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:02:04] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:02:05] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:02:05] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:02:06] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:02:06] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\tests\test_file_handler.py", line 3 in <module>
[2024-10-25 18:02:07] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\assertion\rewrite.py", line 186 in exec_module
[2024-10-25 18:02:08] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:02:08] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:02:09] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:02:09] Output: File "<frozen importlib._bootstrap>", line 1006 in _gcd_import
[2024-10-25 18:02:10] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\importlib\__init__.py", line 127 in import_module
[2024-10-25 18:02:10] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\pathlib.py", line 567 in import_path
[2024-10-25 18:02:11] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 617 in _importtestmodule
[2024-10-25 18:02:12] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 528 in _getobj
[2024-10-25 18:02:13] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 310 in obj
[2024-10-25 18:02:14] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 545 in _inject_setup_module_fixture
[2024-10-25 18:02:14] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 531 in collect
[2024-10-25 18:02:15] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in <lambda>
[2024-10-25 18:02:16] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 341 in from_call
[2024-10-25 18:02:17] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in pytest_make_collect_report
[2024-10-25 18:02:17] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:02:18] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:02:19] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:02:19] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 547 in collect_one_node
[2024-10-25 18:02:20] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 842 in genitems
[2024-10-25 18:02:20] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 675 in perform_collect
[2024-10-25 18:02:21] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 335 in pytest_collection
[2024-10-25 18:02:22] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:02:23] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:02:24] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:06:48] Command: python -m scripts.cli test -t unit
[2024-10-25 18:06:52] Output: ============================= test session starts =============================
[2024-10-25 18:06:52] Output: platform win32 -- Python 3.7.11, pytest-7.4.4, pluggy-1.2.0 -- C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\python.exe
[2024-10-25 18:06:52] Output: cachedir: .pytest_cache
[2024-10-25 18:06:52] Output: rootdir: C:\Users\A.A919579\Samantha\iamanarcpygenius
[2024-10-25 18:06:53] Output: configfile: pytest.ini
[2024-10-25 18:06:53] Output: plugins: cov-4.1.0
[2024-10-25 18:06:53] Output: collecting ... collected 2 items / 2 deselected / 0 selected
[2024-10-25 18:06:53] Output: 
[2024-10-25 18:06:53] Output: ============================ 2 deselected in 0.03s ============================
[2024-10-25 18:07:22] Command: python -m scripts.cli test -t integration
[2024-10-25 18:07:27] Output: ============================= test session starts =============================
[2024-10-25 18:07:27] Output: platform win32 -- Python 3.7.11, pytest-7.4.4, pluggy-1.2.0 -- C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\python.exe
[2024-10-25 18:07:27] Output: cachedir: .pytest_cache
[2024-10-25 18:07:27] Output: rootdir: C:\Users\A.A919579\Samantha\iamanarcpygenius
[2024-10-25 18:07:28] Output: configfile: pytest.ini
[2024-10-25 18:07:28] Output: plugins: cov-4.1.0
[2024-10-25 18:07:28] Output: collecting ... collected 2 items
[2024-10-25 18:07:29] Output: 
[2024-10-25 18:07:29] Output: tests/integration/test_arcpy_operations.py::test_real_arcpy_operations FAILED [ 50%]
[2024-10-25 18:07:29] Output: tests/integration/test_arcpy_operations.py::test_process_real_mxd SKIPPED [100%]
[2024-10-25 18:07:29] Output: 
[2024-10-25 18:07:30] Output: ================================== FAILURES ===================================
[2024-10-25 18:07:30] Output: _________________________ test_real_arcpy_operations __________________________
[2024-10-25 18:07:30] Output: tests\integration\test_arcpy_operations.py:9: in test_real_arcpy_operations
[2024-10-25 18:07:30] Output: assert hasattr(real_arcpy, 'mapping')
[2024-10-25 18:07:30] Output: E   AssertionError
[2024-10-25 18:07:31] Output: =========================== short test summary info ===========================
[2024-10-25 18:07:31] Output: FAILED tests/integration/test_arcpy_operations.py::test_real_arcpy_operations
[2024-10-25 18:07:31] Output: ======================== 1 failed, 1 skipped in 0.16s =========================
[2024-10-25 18:07:51] Command: python -m scripts.cli test -t all
[2024-10-25 18:07:55] Output: ============================= test session starts =============================
[2024-10-25 18:07:56] Output: platform win32 -- Python 3.7.11, pytest-7.4.4, pluggy-1.2.0 -- C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\python.exe
[2024-10-25 18:07:56] Output: cachedir: .pytest_cache
[2024-10-25 18:07:56] Output: rootdir: C:\Users\A.A919579\Samantha\iamanarcpygenius
[2024-10-25 18:07:56] Output: configfile: pytest.ini
[2024-10-25 18:07:57] Output: plugins: cov-4.1.0
[2024-10-25 18:07:57] Output: collecting ... collected 4 items
[2024-10-25 18:07:57] Output: 
[2024-10-25 18:07:57] Output: tests/unit/test_file_handler.py::test_validate_file ERROR                [ 25%]
[2024-10-25 18:07:58] Output: tests/unit/test_file_handler.py::test_process_file_mxd ERROR             [ 50%]
[2024-10-25 18:07:58] Output: tests/integration/test_arcpy_operations.py::test_real_arcpy_operations FAILED [ 75%]
[2024-10-25 18:07:58] Output: tests/integration/test_arcpy_operations.py::test_process_real_mxd SKIPPED [100%]
[2024-10-25 18:07:58] Output: 
[2024-10-25 18:07:58] Output: =================================== ERRORS ====================================
[2024-10-25 18:07:59] Output: ____________________ ERROR at setup of test_validate_file _____________________
[2024-10-25 18:07:59] Output: tests\conftest.py:7: in mock_arcpy
[2024-10-25 18:07:59] Output: with patch('scripts.file_handler.arcpy') as mock:
[2024-10-25 18:07:59] Output: ..\..\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\unittest\mock.py:1307: in __enter__
[2024-10-25 18:08:00] Output: original, local = self.get_original()
[2024-10-25 18:08:00] Output: ..\..\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\unittest\mock.py:1281: in get_original
[2024-10-25 18:08:00] Output: "%s does not have the attribute %r" % (target, name)
[2024-10-25 18:08:00] Output: E   AttributeError: <module 'scripts.file_handler' from 'C:\\Users\\A.A919579\\Samantha\\iamanarcpygenius\\scripts\\file_handler.py'> does not have the attribute 'arcpy'
[2024-10-25 18:08:00] Output: ___________________ ERROR at setup of test_process_file_mxd ___________________
[2024-10-25 18:08:01] Output: tests\conftest.py:7: in mock_arcpy
[2024-10-25 18:08:01] Output: with patch('scripts.file_handler.arcpy') as mock:
[2024-10-25 18:08:01] Output: ..\..\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\unittest\mock.py:1307: in __enter__
[2024-10-25 18:08:01] Output: original, local = self.get_original()
[2024-10-25 18:08:02] Output: ..\..\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\unittest\mock.py:1281: in get_original
[2024-10-25 18:08:02] Output: "%s does not have the attribute %r" % (target, name)
[2024-10-25 18:08:02] Output: E   AttributeError: <module 'scripts.file_handler' from 'C:\\Users\\A.A919579\\Samantha\\iamanarcpygenius\\scripts\\file_handler.py'> does not have the attribute 'arcpy'
[2024-10-25 18:08:02] Output: ================================== FAILURES ===================================
[2024-10-25 18:08:03] Output: _________________________ test_real_arcpy_operations __________________________
[2024-10-25 18:08:03] Output: tests\integration\test_arcpy_operations.py:9: in test_real_arcpy_operations
[2024-10-25 18:08:03] Output: assert hasattr(real_arcpy, 'mapping')
[2024-10-25 18:08:03] Output: E   AssertionError: assert False
[2024-10-25 18:08:04] Output: E    +  where False = hasattr(<module 'arcpy' from 'C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\__init__.py'>, 'mapping')
[2024-10-25 18:08:04] Output: =========================== short test summary info ===========================
[2024-10-25 18:08:04] Output: FAILED tests/integration/test_arcpy_operations.py::test_real_arcpy_operations
[2024-10-25 18:08:04] Output: ERROR tests/unit/test_file_handler.py::test_validate_file - AttributeError: <...
[2024-10-25 18:08:05] Output: ERROR tests/unit/test_file_handler.py::test_process_file_mxd - AttributeError...
[2024-10-25 18:08:05] Output: =================== 1 failed, 1 skipped, 2 errors in 0.51s ====================
[2024-10-25 18:08:41] Command: echo $0
[2024-10-25 18:08:41] Output: /usr/bin/bash
[2024-10-25 18:13:30] Command: ./run_this.sh 
[2024-10-25 18:13:31] Output: Running unit tests...
[2024-10-25 18:13:36] Output: ============================= test session starts =============================
[2024-10-25 18:13:36] Output: platform win32 -- Python 3.7.11, pytest-7.4.4, pluggy-1.2.0 -- C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\python.exe
[2024-10-25 18:13:36] Output: cachedir: .pytest_cache
[2024-10-25 18:13:37] Output: rootdir: C:\Users\A.A919579\Samantha\iamanarcpygenius
[2024-10-25 18:13:37] Output: configfile: pytest.ini
[2024-10-25 18:13:37] Output: plugins: cov-4.1.0
[2024-10-25 18:13:37] Output: collecting ... collected 2 items / 2 deselected / 0 selected
[2024-10-25 18:13:38] Output: 
[2024-10-25 18:13:38] Output: ============================ 2 deselected in 0.03s ============================
[2024-10-25 18:13:38] Output: 
[2024-10-25 18:13:38] Output: Running integration tests...
[2024-10-25 18:13:41] Output: ============================= test session starts =============================
[2024-10-25 18:13:41] Output: platform win32 -- Python 3.7.11, pytest-7.4.4, pluggy-1.2.0 -- C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\python.exe
[2024-10-25 18:13:42] Output: cachedir: .pytest_cache
[2024-10-25 18:13:42] Output: rootdir: C:\Users\A.A919579\Samantha\iamanarcpygenius
[2024-10-25 18:13:42] Output: configfile: pytest.ini
[2024-10-25 18:13:43] Output: plugins: cov-4.1.0
[2024-10-25 18:13:43] Output: collecting ... collected 2 items
[2024-10-25 18:13:44] Output: 
[2024-10-25 18:13:44] Output: tests/integration/test_arcpy_operations.py::test_real_arcpy_operations PASSED [ 50%]
[2024-10-25 18:13:44] Output: tests/integration/test_arcpy_operations.py::test_process_real_mxd SKIPPED [100%]
[2024-10-25 18:13:45] Output: 
[2024-10-25 18:13:45] Output: ======================== 1 passed, 1 skipped in 0.04s =========================
[2024-10-25 18:13:45] Output: 
[2024-10-25 18:13:46] Output: Running all tests with coverage...
[2024-10-25 18:13:46] Output: ============================= test session starts =============================
[2024-10-25 18:13:46] Output: platform win32 -- Python 3.7.11, pytest-7.4.4, pluggy-1.2.0 -- C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\python.exe
[2024-10-25 18:13:46] Output: cachedir: .pytest_cache
[2024-10-25 18:13:47] Output: rootdir: C:\Users\A.A919579\Samantha\iamanarcpygenius
[2024-10-25 18:13:47] Output: configfile: pytest.ini
[2024-10-25 18:13:47] Output: plugins: cov-4.1.0
[2024-10-25 18:13:47] Output: collecting ... Windows fatal exception: code 0xe0000001
[2024-10-25 18:13:48] Output: 
[2024-10-25 18:13:48] Output: Current thread 0x00003058 (most recent call first):
[2024-10-25 18:13:48] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 70 in __init__
[2024-10-25 18:13:49] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 617 in <module>
[2024-10-25 18:13:49] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:13:50] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:13:50] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:13:50] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:13:51] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:13:51] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14 in <module>
[2024-10-25 18:13:51] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:13:52] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:13:52] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:13:53] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:13:53] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:13:53] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 88 in <module>
[2024-10-25 18:13:54] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:13:54] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:13:55] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:13:55] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:13:56] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:13:56] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\process_mxd.py", line 1 in <module>
[2024-10-25 18:13:56] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:13:57] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:13:57] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:13:58] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:13:58] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:13:58] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\file_handler.py", line 4 in <module>
[2024-10-25 18:13:59] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:13:59] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:14:00] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:14:00] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:14:01] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:14:01] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\tests\test_file_handler.py", line 3 in <module>
[2024-10-25 18:14:02] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\assertion\rewrite.py", line 186 in exec_module
[2024-10-25 18:14:02] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:14:03] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:14:03] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:14:03] Output: File "<frozen importlib._bootstrap>", line 1006 in _gcd_import
[2024-10-25 18:14:04] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\importlib\__init__.py", line 127 in import_module
[2024-10-25 18:14:04] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\pathlib.py", line 567 in import_path
[2024-10-25 18:14:05] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 617 in _importtestmodule
[2024-10-25 18:14:06] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 528 in _getobj
[2024-10-25 18:14:07] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 310 in obj
[2024-10-25 18:14:07] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 545 in _inject_setup_module_fixture
[2024-10-25 18:14:08] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 531 in collect
[2024-10-25 18:14:09] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in <lambda>
[2024-10-25 18:14:09] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 341 in from_call
[2024-10-25 18:14:10] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in pytest_make_collect_report
[2024-10-25 18:14:10] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:14:11] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:14:11] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:14:12] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 547 in collect_one_node
[2024-10-25 18:14:13] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 842 in genitems
[2024-10-25 18:14:14] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 675 in perform_collect
[2024-10-25 18:14:14] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 335 in pytest_collection
[2024-10-25 18:14:15] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:14:16] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:14:16] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:14:17] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 324 in _main
[2024-10-25 18:14:17] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 271 in wrap_session
[2024-10-25 18:14:18] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 318 in pytest_cmdline_main
[2024-10-25 18:14:18] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:14:19] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:14:19] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:14:20] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 170 in main
[2024-10-25 18:14:20] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 192 in console_main
[2024-10-25 18:14:21] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pytest\__main__.py", line 5 in <module>
[2024-10-25 18:14:22] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 85 in _run_code
[2024-10-25 18:14:22] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 193 in _run_module_as_main
[2024-10-25 18:14:22] Output: Windows fatal exception: code 0xe0000001
[2024-10-25 18:14:23] Output: 
[2024-10-25 18:14:23] Output: Current thread 0x00003058 (most recent call first):
[2024-10-25 18:14:24] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 70 in __init__
[2024-10-25 18:14:24] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 617 in <module>
[2024-10-25 18:14:25] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:14:26] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:14:26] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:14:26] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:14:27] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:14:27] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14 in <module>
[2024-10-25 18:14:27] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:14:28] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:14:28] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:14:28] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:14:29] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:14:29] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 88 in <module>
[2024-10-25 18:14:30] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:14:30] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:14:30] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:14:31] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:14:31] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:14:32] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\process_mxd.py", line 1 in <module>
[2024-10-25 18:14:32] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:14:33] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:14:33] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:14:34] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:14:34] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:14:35] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\file_handler.py", line 4 in <module>
[2024-10-25 18:14:35] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:14:36] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:14:36] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:14:36] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:14:37] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:14:37] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\tests\test_file_handler.py", line 3 in <module>
[2024-10-25 18:14:38] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\assertion\rewrite.py", line 186 in exec_module
[2024-10-25 18:14:38] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:14:38] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:14:39] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:14:39] Output: File "<frozen importlib._bootstrap>", line 1006 in _gcd_import
[2024-10-25 18:14:40] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\importlib\__init__.py", line 127 in import_module
[2024-10-25 18:14:41] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\pathlib.py", line 567 in import_path
[2024-10-25 18:14:41] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 617 in _importtestmodule
[2024-10-25 18:14:42] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 528 in _getobj
[2024-10-25 18:14:42] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 310 in obj
[2024-10-25 18:14:43] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 545 in _inject_setup_module_fixture
[2024-10-25 18:14:43] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 531 in collect
[2024-10-25 18:14:44] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in <lambda>
[2024-10-25 18:14:44] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 341 in from_call
[2024-10-25 18:14:45] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in pytest_make_collect_report
[2024-10-25 18:14:46] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:14:46] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:14:47] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:14:48] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 547 in collect_one_node
[2024-10-25 18:14:48] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 842 in genitems
[2024-10-25 18:14:49] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 675 in perform_collect
[2024-10-25 18:14:49] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 335 in pytest_collection
[2024-10-25 18:14:50] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:14:50] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:14:51] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:14:51] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 324 in _main
[2024-10-25 18:14:51] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 271 in wrap_session
[2024-10-25 18:14:52] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 318 in pytest_cmdline_main
[2024-10-25 18:14:52] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:14:53] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:14:53] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:14:54] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 170 in main
[2024-10-25 18:14:55] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 192 in console_main
[2024-10-25 18:14:55] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pytest\__main__.py", line 5 in <module>
[2024-10-25 18:14:56] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 85 in _run_code
[2024-10-25 18:14:56] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 193 in _run_module_as_main
[2024-10-25 18:14:57] Output: Windows fatal exception: code 0xe0000001
[2024-10-25 18:14:57] Output: 
[2024-10-25 18:14:57] Output: Current thread 0x00003058 (most recent call first):
[2024-10-25 18:14:57] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 70 in __init__
[2024-10-25 18:14:58] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 617 in <module>
[2024-10-25 18:14:58] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:14:58] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:14:59] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:14:59] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:14:59] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:00] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14 in <module>
[2024-10-25 18:15:01] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:15:01] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:15:02] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:15:02] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:15:03] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:03] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 88 in <module>
[2024-10-25 18:15:04] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:15:04] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:15:05] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:15:05] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:15:06] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:06] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\process_mxd.py", line 1 in <module>
[2024-10-25 18:15:07] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:15:07] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:15:07] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:15:08] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:15:08] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:09] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\file_handler.py", line 4 in <module>
[2024-10-25 18:15:09] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:15:10] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:15:10] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:15:11] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:15:12] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:12] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\tests\test_file_handler.py", line 3 in <module>
[2024-10-25 18:15:13] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\assertion\rewrite.py", line 186 in exec_module
[2024-10-25 18:15:14] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:15:15] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:15:16] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:16] Output: File "<frozen importlib._bootstrap>", line 1006 in _gcd_import
[2024-10-25 18:15:17] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\importlib\__init__.py", line 127 in import_module
[2024-10-25 18:15:18] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\pathlib.py", line 567 in import_path
[2024-10-25 18:15:18] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 617 in _importtestmodule
[2024-10-25 18:15:19] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 528 in _getobj
[2024-10-25 18:15:20] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 310 in obj
[2024-10-25 18:15:20] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 545 in _inject_setup_module_fixture
[2024-10-25 18:15:21] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 531 in collect
[2024-10-25 18:15:21] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in <lambda>
[2024-10-25 18:15:22] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 341 in from_call
[2024-10-25 18:15:22] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in pytest_make_collect_report
[2024-10-25 18:15:23] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:15:24] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:15:24] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:15:25] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 547 in collect_one_node
[2024-10-25 18:15:26] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 842 in genitems
[2024-10-25 18:15:26] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 675 in perform_collect
[2024-10-25 18:15:27] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 335 in pytest_collection
[2024-10-25 18:15:27] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:15:28] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:15:28] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:15:29] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 324 in _main
[2024-10-25 18:15:30] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 271 in wrap_session
[2024-10-25 18:15:30] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 318 in pytest_cmdline_main
[2024-10-25 18:15:31] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:15:31] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:15:32] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:15:32] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 170 in main
[2024-10-25 18:15:32] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 192 in console_main
[2024-10-25 18:15:33] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pytest\__main__.py", line 5 in <module>
[2024-10-25 18:15:34] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 85 in _run_code
[2024-10-25 18:15:35] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 193 in _run_module_as_main
[2024-10-25 18:15:35] Output: Windows fatal exception: code 0xe0000001
[2024-10-25 18:15:35] Output: 
[2024-10-25 18:15:36] Output: Current thread 0x00003058 (most recent call first):
[2024-10-25 18:15:36] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 70 in __init__
[2024-10-25 18:15:37] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 617 in <module>
[2024-10-25 18:15:38] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:15:38] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:15:39] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:15:39] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:15:39] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:40] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14 in <module>
[2024-10-25 18:15:40] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:15:41] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:15:41] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:15:41] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:15:42] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:42] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 88 in <module>
[2024-10-25 18:15:42] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:15:43] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:15:43] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:15:44] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:15:44] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:45] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\process_mxd.py", line 1 in <module>
[2024-10-25 18:15:45] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:15:46] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:15:46] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:15:47] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:15:47] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:48] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\file_handler.py", line 4 in <module>
[2024-10-25 18:15:48] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:15:48] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:15:49] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:15:49] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:15:49] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:49] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\tests\test_file_handler.py", line 3 in <module>
[2024-10-25 18:15:50] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\assertion\rewrite.py", line 186 in exec_module
[2024-10-25 18:15:51] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:15:51] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:15:51] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:15:52] Output: File "<frozen importlib._bootstrap>", line 1006 in _gcd_import
[2024-10-25 18:15:52] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\importlib\__init__.py", line 127 in import_module
[2024-10-25 18:15:53] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\pathlib.py", line 567 in import_path
[2024-10-25 18:15:54] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 617 in _importtestmodule
[2024-10-25 18:15:55] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 528 in _getobj
[2024-10-25 18:15:55] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 310 in obj
[2024-10-25 18:15:56] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 545 in _inject_setup_module_fixture
[2024-10-25 18:15:56] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 531 in collect
[2024-10-25 18:15:57] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in <lambda>
[2024-10-25 18:15:57] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 341 in from_call
[2024-10-25 18:15:58] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in pytest_make_collect_report
[2024-10-25 18:15:58] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:15:59] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:15:59] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:16:00] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 547 in collect_one_node
[2024-10-25 18:16:01] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 842 in genitems
[2024-10-25 18:16:01] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 675 in perform_collect
[2024-10-25 18:16:02] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 335 in pytest_collection
[2024-10-25 18:16:03] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:16:03] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:16:04] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:16:04] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 324 in _main
[2024-10-25 18:16:05] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 271 in wrap_session
[2024-10-25 18:16:06] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 318 in pytest_cmdline_main
[2024-10-25 18:16:07] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:16:08] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:18:46] Command: ./run_this.sh 
[2024-10-25 18:18:47] Output: Verifying pytest installation...
[2024-10-25 18:18:51] Output: 2024-10-25 18:18:51,007 - scripts.helpers.verify_setup - INFO - Starting environment verification...
[2024-10-25 18:18:51] Output: 2024-10-25 18:18:51,007 - scripts.helpers.verify_setup - INFO - Python version: 3.7.11
[2024-10-25 18:18:52] Output: 2024-10-25 18:18:51,007 - scripts.helpers.verify_setup - INFO - \u2713 arcpy (for ArcGIS installation)
[2024-10-25 18:18:52] Output: 2024-10-25 18:18:51,007 - scripts.helpers.verify_setup - INFO - \u2713 click (for CLI support)
[2024-10-25 18:18:52] Output: 2024-10-25 18:18:51,834 - scripts.helpers.verify_setup - INFO - \u2713 pandas (for Data processing)
[2024-10-25 18:18:53] Output: 2024-10-25 18:18:51,835 - scripts.helpers.verify_setup - INFO - \u2713 yaml (for Configuration)
[2024-10-25 18:18:53] Output: 2024-10-25 18:18:52,059 - scripts.helpers.verify_setup - INFO - \u2713 pytest (for Testing)
[2024-10-25 18:18:53] Output: 2024-10-25 18:18:52,059 - scripts.helpers.verify_setup - INFO - \u2713 ArcPy environment configured successfully
[2024-10-25 18:18:53] Output: 2024-10-25 18:18:52,066 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\input\mxd
[2024-10-25 18:18:53] Output: 2024-10-25 18:18:52,066 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\input\aprx
[2024-10-25 18:18:54] Output: 2024-10-25 18:18:52,066 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\output\pdf
[2024-10-25 18:18:54] Output: 2024-10-25 18:18:52,066 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\output\logs
[2024-10-25 18:18:54] Output: 2024-10-25 18:18:52,066 - scripts.helpers.verify_setup - INFO - \u2713 All verification checks passed
[2024-10-25 18:18:55] Output: Environment verification successful!
[2024-10-25 18:18:55] Output: 
[2024-10-25 18:18:56] Output: Running unit tests...
[2024-10-25 18:18:56] Output: ============================= test session starts =============================
[2024-10-25 18:18:56] Output: platform win32 -- Python 3.7.11, pytest-7.4.4, pluggy-1.2.0 -- C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\python.exe
[2024-10-25 18:18:56] Output: cachedir: .pytest_cache
[2024-10-25 18:18:56] Output: rootdir: C:\Users\A.A919579\Samantha\iamanarcpygenius
[2024-10-25 18:18:57] Output: configfile: pytest.ini
[2024-10-25 18:18:57] Output: plugins: cov-4.1.0
[2024-10-25 18:18:57] Output: collecting ... Windows fatal exception: code 0xe0000001
[2024-10-25 18:18:58] Output: 
[2024-10-25 18:18:58] Output: Current thread 0x000036e4 (most recent call first):
[2024-10-25 18:18:59] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 70 in __init__
[2024-10-25 18:18:59] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 617 in <module>
[2024-10-25 18:19:00] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:00] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:01] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:01] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:02] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:02] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14 in <module>
[2024-10-25 18:19:03] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:03] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:04] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:04] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:05] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:06] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 88 in <module>
[2024-10-25 18:19:06] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:06] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:07] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:07] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:08] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:08] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\process_mxd.py", line 1 in <module>
[2024-10-25 18:19:09] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:09] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:10] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:11] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:11] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:12] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\file_handler.py", line 4 in <module>
[2024-10-25 18:19:12] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:13] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:14] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:14] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:15] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:16] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\tests\unit\test_file_handler.py", line 3 in <module>
[2024-10-25 18:19:16] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:17] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:17] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:18] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:18] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:18] Output: File "<frozen importlib._bootstrap>", line 1006 in _gcd_import
[2024-10-25 18:19:19] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\importlib\__init__.py", line 127 in import_module
[2024-10-25 18:19:19] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\pathlib.py", line 567 in import_path
[2024-10-25 18:19:20] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 617 in _importtestmodule
[2024-10-25 18:19:20] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 528 in _getobj
[2024-10-25 18:19:21] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 310 in obj
[2024-10-25 18:19:22] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 545 in _inject_setup_module_fixture
[2024-10-25 18:19:22] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 531 in collect
[2024-10-25 18:19:23] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in <lambda>
[2024-10-25 18:19:24] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 341 in from_call
[2024-10-25 18:19:25] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in pytest_make_collect_report
[2024-10-25 18:19:25] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:19:26] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:19:27] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:19:27] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 547 in collect_one_node
[2024-10-25 18:19:28] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 842 in genitems
[2024-10-25 18:19:29] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 675 in perform_collect
[2024-10-25 18:19:29] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 335 in pytest_collection
[2024-10-25 18:19:29] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:19:30] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:19:31] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:19:31] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 324 in _main
[2024-10-25 18:19:32] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 271 in wrap_session
[2024-10-25 18:19:32] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 318 in pytest_cmdline_main
[2024-10-25 18:19:33] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:19:33] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:19:34] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:19:34] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 170 in main
[2024-10-25 18:19:35] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 192 in console_main
[2024-10-25 18:19:36] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pytest\__main__.py", line 5 in <module>
[2024-10-25 18:19:36] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 85 in _run_code
[2024-10-25 18:19:37] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 193 in _run_module_as_main
[2024-10-25 18:19:38] Output: Windows fatal exception: code 0xe0000001
[2024-10-25 18:19:38] Output: 
[2024-10-25 18:19:39] Output: Current thread 0x000036e4 (most recent call first):
[2024-10-25 18:19:40] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 70 in __init__
[2024-10-25 18:19:41] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 617 in <module>
[2024-10-25 18:19:41] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:42] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:43] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:44] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:44] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:45] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14 in <module>
[2024-10-25 18:19:45] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:46] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:46] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:47] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:47] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:48] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 88 in <module>
[2024-10-25 18:19:48] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:48] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:49] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:49] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:50] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:50] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\process_mxd.py", line 1 in <module>
[2024-10-25 18:19:51] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:51] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:52] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:52] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:53] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:53] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\scripts\file_handler.py", line 4 in <module>
[2024-10-25 18:19:53] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:54] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:54] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:55] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:56] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:56] Output: File "C:\Users\A.A919579\Samantha\iamanarcpygenius\tests\unit\test_file_handler.py", line 3 in <module>
[2024-10-25 18:19:57] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:19:57] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:19:58] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:19:58] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:19:59] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:19:59] Output: File "<frozen importlib._bootstrap>", line 1006 in _gcd_import
[2024-10-25 18:20:00] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\importlib\__init__.py", line 127 in import_module
[2024-10-25 18:20:01] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\pathlib.py", line 567 in import_path
[2024-10-25 18:20:01] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 617 in _importtestmodule
[2024-10-25 18:20:02] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 528 in _getobj
[2024-10-25 18:20:03] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 310 in obj
[2024-10-25 18:20:04] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 545 in _inject_setup_module_fixture
[2024-10-25 18:20:04] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\python.py", line 531 in collect
[2024-10-25 18:20:05] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in <lambda>
[2024-10-25 18:20:06] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 341 in from_call
[2024-10-25 18:20:07] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 372 in pytest_make_collect_report
[2024-10-25 18:20:08] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:20:08] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:20:09] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:20:10] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\runner.py", line 547 in collect_one_node
[2024-10-25 18:20:10] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 842 in genitems
[2024-10-25 18:20:11] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 675 in perform_collect
[2024-10-25 18:20:11] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 335 in pytest_collection
[2024-10-25 18:20:12] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:20:13] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:20:13] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:20:14] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 324 in _main
[2024-10-25 18:20:15] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 271 in wrap_session
[2024-10-25 18:20:16] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\main.py", line 318 in pytest_cmdline_main
[2024-10-25 18:20:16] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
[2024-10-25 18:20:17] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
[2024-10-25 18:20:18] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
[2024-10-25 18:20:18] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 170 in main
[2024-10-25 18:20:19] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\_pytest\config\__init__.py", line 192 in console_main
[2024-10-25 18:20:19] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pytest\__main__.py", line 5 in <module>
[2024-10-25 18:20:20] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 85 in _run_code
[2024-10-25 18:20:20] Output: File "C:\Users\A.A919579\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\runpy.py", line 193 in _run_module_as_main
[2024-10-25 18:20:20] Output: Windows fatal exception: code 0xe0000001
[2024-10-25 18:20:20] Output: 
[2024-10-25 18:20:21] Output: Current thread 0x000036e4 (most recent call first):
[2024-10-25 18:20:22] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 70 in __init__
[2024-10-25 18:20:22] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 617 in <module>
[2024-10-25 18:20:22] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:20:23] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:20:23] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:20:24] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:20:25] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:20:25] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\__init__.py", line 14 in <module>
[2024-10-25 18:20:26] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:20:26] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:20:27] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:20:28] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:20:28] Output: File "<frozen importlib._bootstrap>", line 983 in _find_and_load
[2024-10-25 18:20:28] Output: File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 88 in <module>
[2024-10-25 18:20:29] Output: File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
[2024-10-25 18:20:29] Output: File "<frozen importlib._bootstrap_external>", line 728 in exec_module
[2024-10-25 18:20:29] Output: File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
[2024-10-25 18:20:30] Output: File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
[2024-10-25 18:22:39] Command: ./run_this.sh 
[2024-10-25 18:22:40] Output: Verifying environment setup...
[2024-10-25 18:22:44] Output: 2024-10-25 18:22:44,513 - scripts.helpers.verify_setup - INFO - Starting environment verification...
[2024-10-25 18:22:44] Output: 2024-10-25 18:22:44,513 - scripts.helpers.verify_setup - INFO - Python version: 3.7.11
[2024-10-25 18:22:45] Output: 2024-10-25 18:22:44,513 - scripts.helpers.verify_setup - INFO - \u2713 arcpy (for ArcGIS installation)
[2024-10-25 18:22:45] Output: 2024-10-25 18:22:44,513 - scripts.helpers.verify_setup - INFO - \u2713 click (for CLI support)
[2024-10-25 18:22:45] Output: 2024-10-25 18:22:45,324 - scripts.helpers.verify_setup - INFO - \u2713 pandas (for Data processing)
[2024-10-25 18:22:45] Output: 2024-10-25 18:22:45,324 - scripts.helpers.verify_setup - INFO - \u2713 yaml (for Configuration)
[2024-10-25 18:22:46] Output: 2024-10-25 18:22:45,324 - scripts.helpers.verify_setup - INFO - \u2713 ArcPy environment configured successfully
[2024-10-25 18:22:46] Output: 2024-10-25 18:22:45,328 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\input\mxd
[2024-10-25 18:22:46] Output: 2024-10-25 18:22:45,328 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\input\aprx
[2024-10-25 18:22:47] Output: 2024-10-25 18:22:45,328 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\output\pdf
[2024-10-25 18:22:47] Output: 2024-10-25 18:22:45,328 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\output\logs
[2024-10-25 18:22:47] Output: 2024-10-25 18:22:45,329 - scripts.helpers.verify_setup - INFO - \u2713 All verification checks passed
[2024-10-25 18:22:48] Output: Environment verification successful!
[2024-10-25 19:30:22] Command: ./run_this.sh 
[2024-10-25 19:30:23] Output: Verifying environment setup...
[2024-10-25 19:30:27] Output: 2024-10-25 19:30:27,281 - scripts.helpers.verify_setup - INFO - Starting environment verification...
[2024-10-25 19:30:27] Output: 2024-10-25 19:30:27,281 - scripts.helpers.verify_setup - INFO - Python version: 3.7.11
[2024-10-25 19:30:28] Output: 2024-10-25 19:30:27,281 - scripts.helpers.verify_setup - INFO - \u2713 arcpy (for ArcGIS installation)
[2024-10-25 19:30:28] Output: 2024-10-25 19:30:27,282 - scripts.helpers.verify_setup - INFO - \u2713 click (for CLI support)
[2024-10-25 19:30:28] Output: 2024-10-25 19:30:28,293 - scripts.helpers.verify_setup - INFO - \u2713 pandas (for Data processing)
[2024-10-25 19:30:28] Output: 2024-10-25 19:30:28,293 - scripts.helpers.verify_setup - INFO - \u2713 yaml (for Configuration)
[2024-10-25 19:30:29] Output: 2024-10-25 19:30:28,293 - scripts.helpers.verify_setup - INFO - \u2713 ArcPy environment configured successfully
[2024-10-25 19:30:29] Output: 2024-10-25 19:30:28,293 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\input\mxd
[2024-10-25 19:30:29] Output: 2024-10-25 19:30:28,293 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\input\aprx
[2024-10-25 19:30:29] Output: 2024-10-25 19:30:28,293 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\output\pdf
[2024-10-25 19:30:30] Output: 2024-10-25 19:30:28,293 - scripts.helpers.verify_setup - INFO - \u2713 Directory exists: C:\Users\A.A919579\Samantha\iamanarcpygenius\data\output\logs
[2024-10-25 19:30:30] Output: 2024-10-25 19:30:28,293 - scripts.helpers.verify_setup - INFO - \u2713 All verification checks passed
[2024-10-25 19:30:31] Output: Environment verification successful!
[2024-10-25 19:30:31] Output: 
[2024-10-25 19:30:31] Output: Select processing mode:
[2024-10-25 19:30:31] Output: 1. GUI Mode
[2024-10-25 19:30:32] Output: 2. Command Line Mode
[2024-10-25 19:30:58] Output: Enter choice (1 or 2): Launching GUI...
